### PR TITLE
Add text box for posting review

### PR DESCRIPTION
**Pull request by aseebart**

### CODE REVIEW

**Comment by aseebart** [comment]
I only changes the play-detail-page but before hand I merged with Charles to get some of the filler code that wasn't in dev yet. I would recommend merging everyone else's code and then mine should only show my work.

**Comment by bencdelaney** [comment]
Because #95 was closed (instead of merged), we actually don't want all the code that was in Charles' branch, we only want your work.

I'm sure there's some Git magic to make that happen super easily, do you know off the top of your head, @chaneberg?

**Comment by chaneberg** [comment]
@B3nD3lan3y I'm just gonna use https://github.com/GFUCABAM/statler/compare/Anthony...charles to incorporate his changes into my new pull request.

**Comment by chaneberg** [comment]
OK, it looks like Anthony didn't change anything. This is identical to my old pull request. See https://github.com/GFUCABAM/statler/compare/Anthony...8096270.

**Comment by chaneberg** [comment]
@aseebart, did you forget to `git push`?

**Comment by bencdelaney** [comment]
This looks good to me, Anthony, but you'll need to merge dev before you merge the request.

**Pull request closed without merging**
