### PR TITLE
JavaScript callbacks, look-and-feel improvements, landing page

### PR DESCRIPTION
**Pull request by chaneberg**
Issues: #106, #112, #132, #81, #133

### CODE REVIEW

**Comment by chaneberg** [comment]
I used the [Cyborg bootstrap theme](https://bootswatch.com/cyborg/) to improve the look and feel. That's what the big CSS file is.

**Comment by chaneberg** [comment]
Screenshots:
capture
capture2
capture
capture

**Comment by bencdelaney** [comment]
:+1: :+1: :+1: 

Very well done.

**Comment by mnijmeh11** [comment]
ok I don't know about getting the pictures for the site.. I will check now with the staff......

**Pull request merged**
